/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mbtorneo;

/**
 *
 * @author Juli
 */
public class llaves extends javax.swing.JFrame {

    /**
     * Creates new form equipos
     */
    public llaves() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelCrear = new javax.swing.JLabel();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setMaximumSize(null);
        jPanel1.setMinimumSize(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.setLayout(null);


        LabelCrear.setFont(new java.awt.Font("Twitchy.TV", 0, 36)); // NOI18N
        LabelCrear.setForeground(new java.awt.Color(255, 255, 255));
        LabelCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LabelCrear.setText("CRUCES");

        LabelCrear.setToolTipText("");
        LabelCrear.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabelCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelCrear.setMaximumSize(new java.awt.Dimension(210003, 290000));
        LabelCrear.setPreferredSize(new java.awt.Dimension(480, 100));
        jPanel1.add(LabelCrear);
        LabelCrear.setBounds(270, 0, 540, 57);

        jLabel1.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(null);
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 80, 150, 45);

        jLabel2.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(null);
        jLabel2.setMinimumSize(null);
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 160, 150, 45);

        jLabel3.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(null);
        jLabel3.setMinimumSize(null);
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 300, 150, 45);

        jLabel4.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(null);
        jLabel4.setMinimumSize(null);
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 380, 150, 45);

        jLabel5.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(null);
        jLabel5.setMinimumSize(null);
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 120, 150, 45);

        jLabel6.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(null);
        jLabel6.setMinimumSize(null);
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 240, 150, 45);

        jLabel7.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(null);
        jLabel7.setMinimumSize(null);
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 340, 150, 45);

        jLabel8.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(null);
        jLabel8.setMinimumSize(null);
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(540, 240, 150, 45);

        jLabel9.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("jLabel9");
        jLabel9.setMaximumSize(null);
        jLabel9.setMinimumSize(null);
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(700, 120, 150, 45);

        jLabel10.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(null);
        jLabel10.setMinimumSize(null);
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(890, 80, 150, 45);

        jLabel11.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel11");
        jLabel11.setMaximumSize(null);
        jLabel11.setMinimumSize(null);
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(890, 160, 150, 45);

        jLabel12.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("jLabel12");
        jLabel12.setMaximumSize(null);
        jLabel12.setMinimumSize(null);
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(700, 340, 150, 45);

        jLabel13.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel13");
        jLabel13.setMaximumSize(null);
        jLabel13.setMinimumSize(null);
        jLabel13.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(890, 300, 150, 45);

        jLabel14.setFont(new java.awt.Font("Twitchy.TV", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("jLabel14");
        jLabel14.setMaximumSize(null);
        jLabel14.setMinimumSize(null);
        jLabel14.setPreferredSize(new java.awt.Dimension(150, 45));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(890, 380, 150, 45);

        jButton1.setText("SIGUIENTE");
        jPanel1.add(jButton1);
        jButton1.setBounds(860, 499, 180, 50);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(290, 270, 90, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(100, 150, 120, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(100, 370, 120, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(850, 370, 120, 10);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(850, 150, 120, 10);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(530, 270, 10, 10);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(690, 270, 90, 10);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)

        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(llaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(llaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(llaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(llaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JLabel LabelCrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;

    // End of variables declaration//GEN-END:variables
}
